version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 bookclub.wsgi:application"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    working_dir: /app
    # Added a step to install 'serve' globally as part of the build process
    command: >
      sh -c "npm install -g serve@14.2.4 && npx serve -s build -l 3000"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  postgres_data:
