services:
  backend:
      build: .
      command: ["sh", "./start.sh"]
      volumes:
        - .:/bookclub
      ports:
        - "8000:8000"
      env_file:
        - ./bookclub/.env
      depends_on:
        - db
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend

  db:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"

volumes:
  postgres_data: