# Generated by Django 4.2.11 on 2024-04-08 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0002_book_list_bookclub"),
    ]

    operations = [
        migrations.AddField(
            model_name="book_list",
            name="books",
            field=models.ManyToManyField(to="books.book"),
        ),
        migrations.AlterField(
            model_name="book_list",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
