# Generated by Django 4.2.11 on 2024-04-09 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0004_alter_book_isbn_alter_book_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookclub",
            name="name",
            field=models.CharField(default="BookClub", max_length=100),
        ),
        migrations.AddField(
            model_name="bookclub",
            name="readers",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
