# Generated by Django 4.2.11 on 2024-04-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_bookclub_name_bookclub_readers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
