# Generated by Django 4.2.11 on 2024-05-31 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0011_remove_meeting_occured_meeting_book_club"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-updated_at", "-created_at"]},
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="book",
        ),
        migrations.AddField(
            model_name="book",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="books.meeting",
            ),
        ),
    ]
