# Generated by Django 4.2.11 on 2024-06-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0013_remove_meeting_book_club_alter_book_meeting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="meeting_date",
            field=models.DateTimeField(),
        ),
    ]
