# Generated by Django 4.2.11 on 2024-06-18 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0014_alter_meeting_meeting_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meeting",
                to="books.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="book_chooser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_chooser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="host",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
