# Generated by Django 4.2.11 on 2024-06-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0018_remove_book_meeting_meeting_book_discussed"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="discussed",
            field=models.BooleanField(default=False),
        ),
    ]
