# Generated by Django 4.2.11 on 2024-06-21 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0019_book_discussed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="book_discussed",
        ),
        migrations.AddField(
            model_name="meeting",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book",
                to="books.book",
            ),
        ),
    ]
