# Generated by Django 4.2.11 on 2024-06-28 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0020_remove_meeting_book_discussed_meeting_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="meeting_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
