# Generated by Django 4.2.11 on 2024-05-18 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0006_alter_book_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="books.book",
            ),
        ),
    ]
