# Generated by Django 4.2.11 on 2024-05-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0007_meeting_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book_list",
            name="books",
            field=models.ManyToManyField(blank=True, to="books.book"),
        ),
    ]
