# Generated by Django 4.2.11 on 2024-05-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0008_alter_book_list_books"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
