# Generated by Django 4.2.11 on 2024-06-06 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0012_alter_book_options_remove_meeting_book_book_meeting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="book_club",
        ),
        migrations.AlterField(
            model_name="book",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmeeting",
                to="books.meeting",
            ),
        ),
    ]
