# Generated by Django 4.2.11 on 2024-06-18 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0015_alter_book_meeting_alter_meeting_book_chooser_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="book_chooser",
        ),
        migrations.AddField(
            model_name="meeting",
            name="chooser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chooser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
