# Generated by Django 4.2.11 on 2024-06-18 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0016_remove_meeting_book_chooser_meeting_chooser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmeeting",
                to="books.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="bookclub",
            name="readers",
            field=models.ManyToManyField(
                related_name="bookclubreaders", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="meeting_date",
            field=models.DateField(),
        ),
    ]
