# Generated by Django 4.2.11 on 2024-06-18 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0017_alter_book_meeting_alter_bookclub_readers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="meeting",
        ),
        migrations.AddField(
            model_name="meeting",
            name="book_discussed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmeeting",
                to="books.book",
            ),
        ),
    ]
