# Generated by Django 4.2.11 on 2024-06-28 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0021_alter_meeting_meeting_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="meeting_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
